import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NavBarComp from "./NavbarComp"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="default">
      <body className={inter.className}>
        <NavBarComp />
        <main>{children}</main>
      </body>
    </html>
  )
}
